### ISSUE TITLE
Problem with the hamburger button in the mobile version of the website

### ISSUE THREAD

**Issue by marcofavorito** [whitemech/whitemech.github.io#38]
The :hamburger: button does not work in the mobile version of the website.

Screenshot:

![image](https://user-images.githubusercontent.com/9467617/83348956-0b81c380-a331-11ea-848b-4cfbc3eee5f7.png)

**Comment by marcofavorito** [comment]
To reproduce, set the browser in "mobile" mode and visit whitemech.github.io .

**Comment by francescofuggitti** [comment]
Thanks! I already noticed it and I'm actively working to solve it
